baseURL = "https://benjaminclos.com"
languageCode = "en-us"
title = "tilde"
theme = "coder"

languagecode = "en"

paginate = 20
usemin=false

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Benjamin Clos"
    description = "My personal website"
    keywords = "blog,developer,personal"
    info = "professional computer tickler"
    avatarurl = "images/avatar.jpg"

    hideCredits = true
    hideCopyright = true

    custom_css=["css/app.css"]

[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase fa-2x"
    weight = 2
    url = "https://keybase.io/ondreian"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ondreian/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/benjaminclos/"


[[menu.main]]
    name = "blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "about"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "projects"
    weight = 3
    url = "/projects/"